name: 'Auto Accept Collabs'
description: 'Github Action to auto accept all collaboration invites'
author: 'kbrashears5'
branding:
  icon: 'upload-cloud'
  color: 'purple'
inputs:
  TOKEN:
    description: 'Personal access token with Repo privileges'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'